In [1]:
import pandas as pd
import re
from bs4 import BeautifulSoup
import requests

In [2]:
URL_1995 ='https://en.wikipedia.org/wiki/1995_Rugby_World_Cup'
response_1995 = requests.get(URL_1995)
soup_1995 = BeautifulSoup(response_1995.text,'html.parser')
div_1995 = soup_1995.find('div', {'id':'mw-content-text'})
summary_1995 = div_1995.find_all('div',{'class':'vevent summary'})

In [3]:
events_1995 = []
for i in summary_1995:
    text = i.text
    events_1995.append(text)

In [4]:
events_clean_1995 = [e.replace('\n',' ').replace('\xa0', ' ').strip() for e in events_1995]
data_1995 = " ".join(events_clean_1995)

In [5]:
data_1995 = data_1995.replace('(a.e.t.)','')

In [6]:
#datemethodregex
date_pattern = re.compile(r'\d{1,2}\s\w*\s1995')
dates = date_pattern.findall(data_1995)
date_list = []
for i in dates:
    date_list.append(i)

In [7]:
#team1
team1_pattern = re.compile(r'1995\s{4,5}(\w*|\w*\s\w*)\s{2,3}')
team1 = team1_pattern.findall(data_1995)
team1_list = []
for i in team1:
    team1_list.append(i)

#team2
team2_pattern = re.compile(r'[–]\d*\s{3,4}(\w*|\w*\s\w*)\s{3,7}\D{3}:')
team2 = team2_pattern.findall(data_1995)
team2_list = []
for i in team2:
    team2_list.append(i)

In [8]:
#score
score_pattern = re.compile(r'\d*[–]\d*')
scores = score_pattern.findall(data_1995)
scores_list = []
for i in scores:
    scores_list.append(i)

In [9]:
#points team 1
pt1_pattern = re.compile(r'\s{2,4}(\d*)[–]\d*\s{2,4}')
pt1 = pt1_pattern.findall(data_1995)
pt1_list = []
for i in pt1:
    pt1_list.append(i)
pt1_list = [ int(x) for x in pt1_list ]

#points team 2 
pt2_pattern = re.compile(r'\s{2,4}\d*[–](\d*)\s{2,4}')
pt2 = pt2_pattern.findall(data_1995)
pt2_list = []
for i in pt2:
    pt2_list.append(i)
pt2_list = [ int(x) for x in pt2_list ]

#total points
total_points_list =[]
for i,j in zip(pt1_list, pt2_list):
    k = i+j
    total_points_list.append(k)

In [10]:
#attendance
attendance_pattern = re.compile(r'Attendance:\s(\d*[,]\d*)')
attendance = attendance_pattern.findall(data_1995)
attendance_list = []
for i in attendance:
    attendance_list.append(i)

In [11]:
#referee
referee_pattern = re.compile(r'Referee:\s(\w*\s\w*)')
referee = referee_pattern.findall(data_1995)
referee_list = []
for i in referee:
    referee_list.append(i)

#referee nationality
ref_nationality_pattern = re.compile(r'[(](\D*\s\D*|\D*)[)]')
ref_nationality = ref_nationality_pattern.findall(data_1995)
referee_nationality_list = []
for i in ref_nationality:
    referee_nationality_list.append(i)

In [12]:
dico_1995 = {'Match Date':date_list,'Home Team': team1_list, 'Away Team' : team2_list, 'Score': scores_list, 'Points Home Team': pt1_list, 'Points Away Team' : pt2_list, 'Total Points': total_points_list, 'Attendance': attendance_list, 'Referee': referee_list, 'Referee Nationality': referee_nationality_list}
df_1995 = pd.DataFrame.from_dict(dico_1995, orient='index')
df_1995 = df_1995.transpose()
df_1995

,Match Date,Home Team,Away Team,Score,Points Home Team,Points Away Team,Total Points,Attendance,Referee,Referee Nationality
0,25 May 1995,South Africa,Australia,27–18,27,18,45,"44,778",Derek Bevan,Wales
1,26 May 1995,Canada,Romania,34–3,34,3,37,"8,000",Colin Hawke,New Zealand
2,30 May 1995,South Africa,Romania,21–8,21,8,29,"45,000",Ken McCartney,Scotland
3,31 May 1995,Australia,Canada,27–11,27,11,38,"16,000",Patrick Robin,France
4,3 June 1995,Australia,Romania,42–3,42,3,45,"15,542",Naoki Saito,Japan
5,3 June 1995,South Africa,Canada,20–0,20,0,20,"31,000",David McHugh,Ireland
6,27 May 1995,Italy,Western Samoa,18–42,18,42,60,"7,868",Joël Dume,France
7,27 May 1995,Argentina,England,18–24,18,24,42,"35,000",Jim Fleming,Scotland
8,30 May 1995,Western Samoa,Argentina,32–26,32,26,58,"7,960",Dave Bishop,New Zealand
9,31 May 1995,England,Italy,27–20,27,20,47,"45,093",Stephen Hilditch,Ireland
10,4 June 1995,Argentina,Italy,25–31,25,31,56,"7,571",Clayton Thomas,Wales
11,4 June 1995,England,Western Samoa,44–22,44,22,66,"35,000",Patrick Robin,France
12,27 May 1995,Japan,Wales,10–57,10,57,67,"15,000",Efrahim Sklar,Argentina
13,27 May 1995,Ireland,New Zealand,19–43,19,43,62,"38,000",Wayne Erickson,Australia
14,31 May 1995,Ireland,Japan,50–28,50,28,78,"15,000",Stef Neethling,South Africa
15,31 May 1995,New Zealand,Wales,34–9,34,9,43,"45,000",Ed Morrison,England
16,4 June 1995,Japan,New Zealand,17–145,17,145,162,"25,000",George Gadjovic,Canada
17,4 June 1995,Ireland,Wales,24–23,24,23,47,"40,000",Ian Rogers,South Africa
18,26 May 1995,Ivory Coast,Scotland,0–89,0,89,89,"20,000",Felise Vito,Western Samoa
19,26 May 1995,France,Tonga,38–10,38,10,48,"22,000",Steve Lander,England
20,29 May 1995,France,Ivory Coast,54–18,54,18,72,"10,000",Han Moon,South Korea
21,29 May 1995,Scotland,Tonga,41–5,41,5,46,"21,000",Barry Leask,Australia
22,3 June 1995,Ivory Coast,Tonga,11–29,11,29,40,"15,000",Don Reordan,United States
23,3 June 1995,France,Scotland,22–19,22,19,41,"39,000",Wayne Erickson,Australia
24,10 June 1995,France,Ireland,36–12,36,12,48,"20,000",Ed Morrison,England
25,10 June 1995,South Africa,Western Samoa,42–14,42,14,56,"54,169",Jim Fleming,Scotland
26,11 June 1995,England,Australia,25–22,25,22,47,"35,448",Dave Bishop,New Zealand
27,11 June 1995,New Zealand,Scotland,48–30,48,30,78,"28,000",Derek Bevan,Wales
28,17 June 1995,South Africa,France,19–15,19,15,34,"49,773",Derek Bevan,Wales
29,18 June 1995,England,New Zealand,29–45,29,45,74,"43,414",Stephen Hilditch,Ireland
30,22 June 1995,France,England,19–9,19,9,28,"44,000",Dave Bishop,New Zealand
31,24 June 1995,South Africa,New Zealand,15–12,15,12,27,"59,870",Ed Morrison,England

In [14]:
# df_1995.to_csv(r'C:\Users\lacar\DQ Projects\Rugby DataVis' + '\\1995.csv', index=False)